import { StyleSheet } from 'react-native';
import { colors } from '@/src/theme/colors';

const MARGEM = 20;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: MARGEM,
    paddingTop: 24,
  },

  avatarContainer: {
    alignItems: 'center',
    marginBottom: 32,
    gap: 8,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primary + '22',
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  avatarLetra: {
    fontFamily: 'Creato-Bold',
    fontSize: 32,
    color: colors.primary,
  },
  nomeUsuario: {
    fontFamily: 'Creato-Bold',
    fontSize: 20,
    color: colors.text,
  },
  membroDesde: {
    fontFamily: 'Creato-Regular',
    fontSize: 13,
    color: colors.text_secondary,
  },

  secao: {
    marginBottom: 28,
    gap: 12,
  },
  secaoDanger: {
    marginBottom: 28,
    gap: 12,
  },
  secaoLabel: {
    fontFamily: 'Creato-Bold',
    color: colors.azulClaro,
    fontSize: 11,
    letterSpacing: 1.4,
    marginBottom: 4,
  },

  campoContainer: {
    gap: 6,
  },
  campoLabel: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 12,
    letterSpacing: 0.6,
  },
  campoInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  campoInputRowAtivo: {
    borderColor: colors.azulClaro,
    backgroundColor: '#0e78ff08',
  },
  campoInput: {
    flex: 1,
    fontFamily: 'Creato-Regular',
    color: colors.text,
    fontSize: 15,
  },

  botoesContainer: {
    gap: 10,
    marginBottom: 32,
  },
  btnEditar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  txtBtnEditar: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 14,
    letterSpacing: 0.8,
  },
  btnSalvar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
  },
  txtBtnSalvar: {
    fontFamily: 'Creato-Bold',
    color: '#FFF',
    fontSize: 14,
    letterSpacing: 0.8,
  },
  btnCancelar: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  txtBtnCancelar: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 13,
  },

  btnExcluir: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.vermelho + '12',
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.vermelho + '44',
  },
  txtBtnExcluir: {
    fontFamily: 'Creato-Bold',
    color: colors.vermelho,
    fontSize: 14,
    letterSpacing: 0.8,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
  },
  modalCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 20,
    padding: 28,
    width: '100%',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  modalTitulo: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 18,
    marginBottom: 4,
  },
  modalSubtitulo: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 8,
  },
  modalBotoes: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
    width: '100%',
  },
  btnNao: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#3a3a3a',
  },
  txtNao: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 13,
    letterSpacing: 0.8,
  },
  btnSim: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: colors.vermelho + '22',
    borderWidth: 1,
    borderColor: colors.vermelho,
  },
  txtSim: {
    fontFamily: 'Creato-Bold',
    color: colors.vermelho,
    fontSize: 13,
    letterSpacing: 0.8,
  },
  toastSucesso: {
  position: 'absolute',
  bottom: 40,
  left: 20,
  right: 20,
  backgroundColor: colors.primary,
  borderRadius: 12,
  paddingVertical: 14,
  paddingHorizontal: 16,
  flexDirection: 'row',
  alignItems: 'center',
  gap: 10,
  elevation: 6,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.3,
  shadowRadius: 6,
},
toastTexto: {
  fontFamily: 'Creato-Bold',
  color: '#FFF',
  fontSize: 14,
  flex: 1,
},
});