import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '@/src/theme/colors';

const { width: SCREEN_W } = Dimensions.get('window');
const MARGEM = 20;

export const styles = StyleSheet.create({
  // ── ROOT ──────────────────────────────────────────────────────────────────
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },

  // ── HEADER ────────────────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: MARGEM,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1e1e1e',
  },
  headerBackBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#1a1a1a',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  headerTitle: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 16,
    letterSpacing: 1.2,
    flex: 1,
  },
  headerEditBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  headerEditBtnText: {
    fontFamily: 'Creato-Bold',
    color: colors.primary,
    fontSize: 12,
    letterSpacing: 0.6,
  },

  // ── HERO PLACAR ───────────────────────────────────────────────────────────
  hero: {
    paddingHorizontal: MARGEM,
    paddingTop: 28,
    paddingBottom: 24,
    alignItems: 'center',
  },
  heroCatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 22,
  },
  heroCatText: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 12,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  heroDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.text_secondary,
  },
  heroTeamsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  heroTeamCol: {
    alignItems: 'center',
    width: (SCREEN_W - MARGEM * 2) * 0.32,
    gap: 10,
  },
  heroLogo: {
    width: 64,
    height: 64,
    resizeMode: 'contain',
    borderRadius: 10,
    backgroundColor: '#1e1e1e',
  },
  heroLogoPlaceholder: {
    width: 64,
    height: 64,
    borderRadius: 10,
    backgroundColor: '#1e1e1e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTeamName: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 13,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  heroScoreBlock: {
    alignItems: 'center',
    gap: 6,
  },
  heroScoreText: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 46,
    letterSpacing: -1,
    lineHeight: 52,
  },
  heroVs: {
    fontFamily: 'Creato-Bold',
    color: '#333',
    fontSize: 18,
    letterSpacing: 2,
  },
  heroScoreSeparator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#333',
    marginHorizontal: 8,
  },

  // Badge ao vivo / finalizado
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.vermelho + '20',
    borderWidth: 1,
    borderColor: colors.vermelho + '55',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 6,
    marginTop: 8,
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.vermelho,
  },
  liveBadgeText: {
    fontFamily: 'Creato-Bold',
    color: colors.vermelho,
    fontSize: 11,
    letterSpacing: 1,
  },
  finishedBadge: {
    backgroundColor: '#1e1e1e',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    marginTop: 8,
  },
  finishedBadgeText: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 11,
    letterSpacing: 1,
  },
  scheduledBadge: {
    backgroundColor: colors.primary + '18',
    borderWidth: 1,
    borderColor: colors.primary + '44',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    marginTop: 8,
  },
  scheduledBadgeText: {
    fontFamily: 'Creato-Bold',
    color: colors.primary,
    fontSize: 11,
    letterSpacing: 1,
  },

  // ── INFO BAR ──────────────────────────────────────────────────────────────
  infoBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#1e1e1e',
    marginHorizontal: MARGEM,
    marginBottom: 28,
  },
  infoBarItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 14,
    gap: 5,
  },
  infoBarDivider: {
    width: 1,
    backgroundColor: '#1e1e1e',
    marginVertical: 10,
  },
  infoBarLabel: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  infoBarValue: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 13,
  },

  // ── SEÇÃO GENÉRICA ────────────────────────────────────────────────────────
  section: {
    paddingHorizontal: MARGEM,
    marginBottom: 28,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionBar: {
    width: 3,
    height: 16,
    backgroundColor: colors.primary,
    borderRadius: 2,
  },
  sectionTitle: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 14,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  sectionAction: {
    fontFamily: 'Creato-Bold',
    color: colors.primary,
    fontSize: 12,
    letterSpacing: 0.5,
  },

  // ── TEMPO PARTIDA ─────────────────────────────────────────────────────────
  periodoRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  periodoBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  periodoBtnAtivo: {
    backgroundColor: colors.primary + '22',
    borderColor: colors.primary + '66',
  },
  periodoBtnText: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 12,
    letterSpacing: 0.8,
  },
  periodoBtnTextAtivo: {
    color: colors.primary,
  },

  // ── GRID DE EVENTOS ───────────────────────────────────────────────────────
  eventsGrid: {
    gap: 10,
  },
  // Gol (stepper largo)
  golCard: {
    backgroundColor: colors.primary + '18',
    borderWidth: 1,
    borderColor: colors.primary + '44',
    borderRadius: 14,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  golLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  golIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: colors.primary + '33',
    alignItems: 'center',
    justifyContent: 'center',
  },
  golLabel: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 15,
    letterSpacing: 0.5,
  },
  golSub: {
    fontFamily: 'Creato-Regular',
    color: colors.primary,
    fontSize: 11,
  },
  golStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  stepBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepBtnMinus: {
    backgroundColor: '#1e1e1e',
    borderWidth: 1,
    borderColor: '#333',
  },
  stepValue: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 22,
    minWidth: 32,
    textAlign: 'center',
  },
  // Grid 2x2 + 1 centralizado
  eventsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  eventCard: {
    flex: 1,
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#252525',
  },
  eventCardCenter: {
    width: '50%',
    alignSelf: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#252525',
  },
  eventIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#252525',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartaoRect: {
    width: 16,
    height: 22,
    borderRadius: 3,
  },
  eventLabel: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 11,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  eventCount: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 20,
  },

  // ── ESCALAÇÃO ─────────────────────────────────────────────────────────────
  jogadorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#252525',
    gap: 12,
  },
  jogadorNumero: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  jogadorNumeroText: {
    fontFamily: 'Creato-Bold',
    color: '#fff',
    fontSize: 12,
  },
  jogadorNome: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 14,
    flex: 1,
  },
  jogadorPos: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 11,
  },
  jogadorStats: {
    flexDirection: 'row',
    gap: 6,
  },
  jogadorStatChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#252525',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 5,
    gap: 3,
  },
  jogadorStatText: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 10,
  },

  // ── MODAL DETALHES JOGADOR ────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.82)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#181818',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: MARGEM,
    paddingTop: 12,
    paddingBottom: 36,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#333',
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalJogadorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    gap: 12,
  },
  modalJogadorNum: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalJogadorNumText: {
    fontFamily: 'Creato-Bold',
    color: '#fff',
    fontSize: 16,
  },
  modalJogadorNome: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 17,
  },
  modalJogadorPos: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 12,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#222',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  statLabel: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 10,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  statStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statStepBtn: {
    width: 28,
    height: 28,
    borderRadius: 7,
    backgroundColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statStepBtnPlus: {
    backgroundColor: colors.primary,
  },
  statStepVal: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 18,
    minWidth: 20,
    textAlign: 'center',
  },
  saveStatBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 10,
  },
  saveStatBtnText: {
    fontFamily: 'Creato-Bold',
    color: '#fff',
    fontSize: 14,
    letterSpacing: 0.8,
  },

  // ── MODAL ALTERAR ESCALAÇÃO ───────────────────────────────────────────────
  fullModal: {
    flex: 1,
    backgroundColor: colors.background,
  },
  fullModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: MARGEM,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1e1e1e',
    gap: 12,
  },
  fullModalTitle: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 16,
    letterSpacing: 1,
    flex: 1,
  },
  escalacaoColumns: {
    flexDirection: 'row',
    flex: 1,
    gap: 0,
  },
  escalacaoColumn: {
    flex: 1,
    padding: 14,
  },
  escalacaoColumnTitle: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 12,
    textAlign: 'center',
  },
  escalacaoColumnDivider: {
    width: 1,
    backgroundColor: '#1e1e1e',
  },
  jogadorSelectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    gap: 10,
    borderWidth: 1,
    borderColor: '#252525',
  },
  jogadorSelectRowActive: {
    borderColor: colors.primary + '88',
    backgroundColor: colors.primary + '12',
  },
  checkBox: {
    width: 20,
    height: 20,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: '#444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  jogadorSelectNome: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 13,
    flex: 1,
  },
  jogadorSelectPos: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 11,
  },
  applyEscalacaoBtn: {
    backgroundColor: colors.primary,
    margin: MARGEM,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
  },
  applyEscalacaoBtnText: {
    fontFamily: 'Creato-Bold',
    color: '#fff',
    fontSize: 14,
    letterSpacing: 0.8,
  },

  // ── BOTÃO FINALIZAR PARTIDA ───────────────────────────────────────────────
  finalizarSection: {
    paddingHorizontal: MARGEM,
    marginBottom: 40,
  },
  finalizarBtn: {
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.vermelho + '55',
    backgroundColor: colors.vermelho + '14',
  },
  finalizarBtnText: {
    fontFamily: 'Creato-Bold',
    color: colors.vermelho,
    fontSize: 14,
    letterSpacing: 1,
  },

  // ── MODAL CONFIRMAÇÃO ─────────────────────────────────────────────────────
  confirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    padding: MARGEM,
  },
  confirmBox: {
    backgroundColor: '#181818',
    borderRadius: 18,
    padding: 26,
    borderWidth: 1,
    borderColor: '#252525',
    gap: 16,
  },
  confirmIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: colors.vermelho + '22',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  confirmTitle: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 17,
    textAlign: 'center',
  },
  confirmDesc: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
  },
  confirmBtnRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  confirmCancel: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: '#222',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333',
  },
  confirmCancelText: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 13,
  },
  confirmOk: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: colors.vermelho,
    alignItems: 'center',
  },
  confirmOkText: {
    fontFamily: 'Creato-Bold',
    color: '#fff',
    fontSize: 13,
  },

  // ── RODAPÉ INFO (PARTIDA FINALIZADA) ─────────────────────────────────────
  metaRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  metaCard: {
    flex: 1,
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 14,
    gap: 5,
    borderWidth: 1,
    borderColor: '#252525',
  },
  metaLabel: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  metaValue: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 13,
  },

  // ── DIVISOR ───────────────────────────────────────────────────────────────
  divider: {
    height: 1,
    backgroundColor: '#1e1e1e',
    marginHorizontal: MARGEM,
    marginBottom: 28,
  },
});