import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '@/src/theme/colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 10,
  },
  buscaContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  buscaInput: {
    flex: 1,
    color: colors.text,
    fontFamily: 'Creato-Bold',
    fontSize: 13,
  },
  filtrosRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
  },
  filtrosPills: {
    flexDirection: 'row',
    gap: 6,
  },
  counterTxt: {
    fontFamily: 'Creato-Bold',
    fontSize: 10,
    color: '#444',
    letterSpacing: 1,
  },
  scoutLoadingTxt: {
    fontFamily: 'Creato-Bold',
    fontSize: 10,
    color: colors.primary,
  },
  lista: {
    paddingHorizontal: 16,
    paddingTop: 4,
  },
  cardAtleta: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141414',
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#1e1e1e',
    gap: 10,
  },
  camisaBox: {
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0d0d0d',
  },
  camisaTxt: {
    fontFamily: 'Creato-Bold',
    fontSize: 13,
  },
  cardInfos: {
    flex: 1,
  },
  cardNome: {
    fontFamily: 'Creato-Bold',
    fontSize: 14,
    color: colors.text,
  },
  cardSub: {
    fontFamily: 'Creato-Bold',
    fontSize: 11,
    color: colors.text_secondary,
  },
  cardDireita: {
    alignItems: 'flex-end',
    gap: 4,
  },
  badgePerfil: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
  },
  badgePerfilTxt: {
    fontFamily: 'Creato-Bold',
    fontSize: 9,
    letterSpacing: 0.5,
  },
  notaTxt: {
    fontFamily: 'Creato-Bold',
    fontSize: 18,
  },
  acoes: {
    flexDirection: 'column',
    gap: 5,
  },
  btnAcao: {
    width: 30,
    height: 30,
    backgroundColor: '#1a1a1a',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  btnAcaoDanger: {
    borderColor: colors.vermelho + '40',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 60,
    gap: 14,
  },
  emptyTxt: {
    fontFamily: 'Creato-Bold',
    color: '#333',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 22,
  },
  fab: {
    position: 'absolute',
    bottom: 28,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    justifyContent: 'flex-end',
  },
  formCard: {
    backgroundColor: '#111',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
  },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  formTitulo: {
    fontFamily: 'Creato-Bold',
    fontSize: 16,
    color: colors.text,
  },
  formLabel: {
    fontFamily: 'Creato-Bold',
    fontSize: 10,
    color: '#555',
    letterSpacing: 1.5,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    gap: 10,
    borderWidth: 1,
    borderColor: '#2a2a2a',
    width: '100%',
  },
  input: {
    flex: 1,
    color: colors.text,
    fontFamily: 'Creato-Bold',
    fontSize: 14,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  pillAtivo: {
    backgroundColor: colors.primary + '18',
    borderColor: colors.primary + '60',
  },
  pillTxt: {
    fontFamily: 'Creato-Bold',
    fontSize: 12,
    color: colors.text_secondary,
  },
  pillTxtAtivo: {
    color: colors.primary,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: colors.azulClaro + '12',
    borderRadius: 10,
    padding: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.azulClaro + '30',
  },
  infoTxt: {
    flex: 1,
    fontFamily: 'Creato-Bold',
    fontSize: 11,
    color: colors.azulClaro,
    lineHeight: 16,
  },
  btnSalvar: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
  },
  btnSalvarTxt: {
    fontFamily: 'Creato-Bold',
    color: '#FFF',
    fontSize: 13,
    letterSpacing: 1,
  },
  confirmCard: {
    backgroundColor: '#111',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    alignItems: 'center',
    gap: 10,
  },
  confirmTxt: {
    fontFamily: 'Creato-Bold',
    fontSize: 13,
    color: colors.text_secondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 8,
  },
  scoutContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scoutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  scoutTitulo: {
    fontFamily: 'Creato-Bold',
    fontSize: 13,
    color: colors.text,
    letterSpacing: 2,
  },
  btnVoltar: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 10,
  },
  scoutScroll: {
    padding: 16,
    paddingBottom: 60,
  },
  identidadeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141414',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    marginBottom: 16,
    gap: 12,
  },
  avatarGradient: {
    width: 54,
    height: 54,
    borderRadius: 13,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarNum: {
    fontFamily: 'Creato-Bold',
    fontSize: 20,
  },
  scoutNome: {
    fontFamily: 'Creato-Bold',
    fontSize: 16,
    color: colors.text,
  },
  scoutPosicao: {
    fontFamily: 'Creato-Bold',
    fontSize: 11,
    color: colors.text_secondary,
    marginTop: 1,
  },
  chip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#333',
  },
  chipTxt: {
    fontFamily: 'Creato-Bold',
    fontSize: 10,
    color: colors.text_secondary,
  },
  notaBox: {
    alignItems: 'center',
  },
  notaLabel: {
    fontFamily: 'Creato-Bold',
    fontSize: 8,
    color: '#444',
    letterSpacing: 1,
  },
  notaValor: {
    fontFamily: 'Creato-Bold',
    fontSize: 34,
  },
  secaoCard: {
    backgroundColor: '#141414',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#1e1e1e',
    marginBottom: 16,
  },
  secaoLabel: {
    fontFamily: 'Creato-Bold',
    fontSize: 9,
    color: '#444',
    letterSpacing: 2,
    marginBottom: 10,
  },
  barRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  barLabel: {
    fontFamily: 'Creato-Bold',
    fontSize: 9,
    color: colors.text_secondary,
    width: 82,
  },
  barBg: {
    flex: 1,
    height: 4,
    backgroundColor: '#2a2a2a',
    borderRadius: 2,
    overflow: 'hidden',
  },
  barFill: {
    height: 4,
    borderRadius: 2,
  },
  barVal: {
    fontFamily: 'Creato-Bold',
    fontSize: 11,
    width: 26,
    textAlign: 'right',
  },
  semDados: {
    alignItems: 'center',
    padding: 32,
    gap: 12,
  },
  semDadosTxt: {
    fontFamily: 'Creato-Bold',
    fontSize: 12,
    color: '#333',
    textAlign: 'center',
    lineHeight: 18,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    minWidth: (width - 48) / 4,
    backgroundColor: '#141414',
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#1e1e1e',
  },
  statValor: {
    fontFamily: 'Creato-Bold',
    fontSize: 20,
    color: colors.text,
  },
  statLabel: {
    fontFamily: 'Creato-Bold',
    fontSize: 9,
    color: colors.text_secondary,
  },
  eficienciaRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  eficienciaCard: {
    flex: 1,
    backgroundColor: '#141414',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#1e1e1e',
  },
  eficienciaValor: {
    fontFamily: 'Creato-Bold',
    fontSize: 22,
    color: colors.text,
  },
  eficienciaLabel: {
    fontFamily: 'Creato-Bold',
    fontSize: 10,
    color: colors.text_secondary,
  },
});